In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df=pd.read_csv("APPLE.csv")

In [3]:
df.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100323  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095089  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088110  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090291   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092908   73449600

In [5]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10409 entries, 0 to 10408
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10409 non-null  object
 1   Open       10409 non-null  float64
 2   High       10409 non-null  float64
 3   Low        10409 non-null  float64
 4   Close      10409 non-null  float64
 5   Adj Close  10409 non-null  float64
 6   Volume     10409 non-null  int64
dtypes: float64(5), int64(1), object(1)
memory usage: 569.4+ KB

In [9]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [15]:
df.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [17]:
print(df.describe)

<bound method NDFrame.describe of              Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.128348    0.128906    0.128348    0.128348    0.100323
1      1980-12-15    0.122210    0.122210    0.121652    0.121652    0.095089
2      1980-12-16    0.113281    0.113281    0.112723    0.112723    0.088110
3      1980-12-17    0.115513    0.116071    0.115513    0.115513    0.090291
4      1980-12-18    0.118862    0.119420    0.118862    0.118862    0.092908
...           ...         ...         ...         ...         ...         ...
10404  2022-03-18  160.509995  164.479996  159.759995  163.979996  163.979996
10405  2022-03-21  163.509995  166.350006  163.009995  165.380005  165.380005
10406  2022-03-22  165.509995  169.419998  164.910004  168.820007  168.820007
10407  2022-03-23  167.990005  172.639999  167.649994  170.210007  170.210007
10408  2022-03-24  171.059998  174.139999  170.210007  174.070007  174.070007

          Volume
0      469033600
1      175884800
2      105728000
3       86441600
4       73449600
...          ...
10404  123351200
10405   95811400
10406   81532000
10407   98062700
10408   90018700

[10409 rows x 7 columns]>

In [18]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [23]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of              Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.128348    0.128906    0.128348    0.128348    0.100323
1      1980-12-15    0.122210    0.122210    0.121652    0.121652    0.095089
2      1980-12-16    0.113281    0.113281    0.112723    0.112723    0.088110
3      1980-12-17    0.115513    0.116071    0.115513    0.115513    0.090291
4      1980-12-18    0.118862    0.119420    0.118862    0.118862    0.092908
...           ...         ...         ...         ...         ...         ...
10404  2022-03-18  160.509995  164.479996  159.759995  163.979996  163.979996
10405  2022-03-21  163.509995  166.350006  163.009995  165.380005  165.380005
10406  2022-03-22  165.509995  169.419998  164.910004  168.820007  168.820007
10407  2022-03-23  167.990005  172.639999  167.649994  170.210007  170.210007
10408  2022-03-24  171.059998  174.139999  170.210007  174.070007  174.070007

          Volume
0      469033600
1      175884800
2      105728000
3       86441600
4       73449600
...          ...
10404  123351200
10405   95811400
10406   81532000
10407   98062700
10408   90018700

[10409 rows x 7 columns]>

In [ ]:
df['Date']

In [36]:
avgopen=df['Open'].mean()
avgclose=df['Close'].mean()

In [38]:
print(avgopen)
print(avgclose)

13.959909858007494
13.966756942837927

In [48]:
df['High'].sort_values
df['Low'].sort_values

highval=df['High'].tail(1)
lowval=df['Low'].head(1)

print(highval)
print(lowval)

10408    174.139999
Name: High, dtype: float64
0    0.128348
Name: Low, dtype: float64

In [54]:
df['Delta']=df['Close']-df['Low']
df['Delta'].tail(10)

10399    0.229996
10400    0.519989
10401    4.709991
10402    5.129989
10403    2.989990
10404    4.220001
10405    2.370010
10406    3.910003
10407    2.560013
10408    3.860000
Name: Delta, dtype: float64

In [56]:
df['Daily_Return']=(df['Delta']/df['Open'])*100
print(df['Daily_Return'])

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...
10404    2.629120
10405    1.449459
10406    2.362397
10407    1.523908
10408    2.256518
Name: Daily_Return, Length: 10409, dtype: float64

In [58]:
df['Daily_Return'].sort_values
df['Daily_Return'].tail(10)

10399    0.144715
10400    0.343340
10401    3.121267
10402    3.266469
10403    1.885121
10404    2.629120
10405    1.449459
10406    2.362397
10407    1.523908
10408    2.256518
Name: Daily_Return, dtype: float64

In [59]:
max=df['Volume'].max()
min=df['Volume'].min()
avg=df['Volume'].mean()
print(avg)
print(min)
print(max)

df['Volume'].sort_values
df['Volume'].tail(10)

332177847.17071766
0
7421640800

10399     96836300
10400    108732100
10401     92964300
10402    102300200
10403     75615400
10404    123351200
10405     95811400
10406     81532000
10407     98062700
10408     90018700
Name: Volume, dtype: int64