In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df=pd.read_csv("healthcare_dataset.csv")

In [33]:
df.head(10)

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD10 I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD10 J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD10 E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD10 J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD10 S52,8500.0,25-01-2026
5,P1006,Female,41,Appendicitis,18-01-2026,Emergency,ICD10 K35,9200.0,21-01-2026
6,P1007,Male,73,Heart Failure,18-01-2026,Routine,NaN,10500.0,28-01-2026
7,P1008,Female,27,Migraine,19-01-2026,Routine,ICD10 G43,2500.0,20-01-2026
8,P1009,Male,58,COPD,19-01-2026,Emergency,ICD10 J44,7800.0,24-01-2026
9,P1010,Female,36,Gastritis,20-01-2026,Urgent,ICD10 K29,3900.0,22-01-2026

In [34]:
df.tail(20)

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
480,P1481,Male,35,Back Pain,12-09-2026,Urgent,ICD10 M54,4700.0,14-09-2026
481,P1482,Female,60,Diabetes Type 1,13-09-2026,Routine,ICD10 E10,5500.0,15-09-2026
482,P1483,Male,73,Heart Attack,13-09-2026,Emergency,ICD10 I21,14100.0,17-09-2026
483,P1484,Female,27,Skin Infection,14-09-2026,Urgent,ICD10 L03,4500.0,16-09-2026
484,P1485,Male,46,Osteoporosis,14-09-2026,Routine,ICD10 M81,5200.0,16-09-2026
485,P1486,Female,64,COPD,15-09-2026,Emergency,ICD10 J44,9700.0,18-09-2026
486,P1487,Male,32,Appendicitis,15-09-2026,Emergency,ICD10 K35,10800.0,17-09-2026
487,P1488,Female,54,Hypertension,16-09-2026,Routine,ICD10 I10,5900.0,18-09-2026
488,P1489,Male,70,Stroke,16-09-2026,Emergency,ICD10 I63,13800.0,20-09-2026
489,P1490,Female,41,Gastritis,17-09-2026,Urgent,ICD10 K29,5000.0,19-09-2026
490,P1491,Male,57,Heart Failure,17-09-2026,Routine,ICD10 I50,12800.0,21-09-2026
491,P1492,Female,29,Pregnancy,18-09-2026,Routine,ICD10 O80,6200.0,20-09-2026
492,P1493,Male,63,Kidney Stone,18-09-2026,Emergency,ICD10 N20,10600.0,20-09-2026
493,P1494,Female,75,Parkinson's Disease,19-09-2026,Routine,ICD10 G20,8300.0,23-09-2026
494,P1495,Male,39,Asthma,19-09-2026,Urgent,ICD10 J45,5900.0,21-09-2026
495,P1496,Female,50,COPD,20-09-2026,Emergency,ICD10 J44,9800.0,23-09-2026
496,P1497,Male,28,Fracture,20-09-2026,Urgent,ICD10 S52,9400.0,24-09-2026
497,P1498,Female,67,Heart Attack,21-09-2026,Emergency,ICD10 I21,14200.0,25-09-2026
498,P1499,Male,43,Diabetes Type 2,21-09-2026,Routine,ICD10 E11,4900.0,23-09-2026
499,P1500,Female,61,Stroke,22-09-2026,Emergency,ICD10 I63,13900.0,26-09-2026

In [35]:
df.columns

Index(['Patient_ID', 'Gender', 'Age', 'Medical_Condition', 'Admission_Date',
       'Admission_Type', 'Medical_Code', 'Billing_Amount', 'Discharge_Date'],
      dtype='object')

In [36]:
df.dtypes

Patient_ID            object
Gender                object
Age                    int64
Medical_Condition     object
Admission_Date        object
Admission_Type        object
Medical_Code          object
Billing_Amount       float64
Discharge_Date        object
dtype: object

In [37]:
df.info

<bound method DataFrame.info of     Patient_ID  Gender  Age Medical_Condition Admission_Date Admission_Type  \
0        P1001    Male   45      Hypertension     15-01-2026         Urgent
1        P1002  Female   32         Pneumonia     16-01-2026      Emergency
2        P1003    Male   68   Diabetes Type 2     16-01-2026        Routine
3        P1004  Female   55            Asthma     17-01-2026      Emergency
4        P1005    Male   29          Fracture     17-01-2026         Urgent
..         ...     ...  ...               ...            ...            ...
495      P1496  Female   50              COPD     20-09-2026      Emergency
496      P1497    Male   28          Fracture     20-09-2026         Urgent
497      P1498  Female   67      Heart Attack     21-09-2026      Emergency
498      P1499    Male   43   Diabetes Type 2     21-09-2026        Routine
499      P1500  Female   61            Stroke     22-09-2026      Emergency

    Medical_Code  Billing_Amount Discharge_Date
0      ICD10 I10          4500.0     20-01-2026
1      ICD10 J18          6700.5     22-01-2026
2      ICD10 E11          3200.0     18-01-2026
3      ICD10 J45          5800.0     19-01-2026
4      ICD10 S52          8500.0     25-01-2026
..           ...             ...            ...
495    ICD10 J44          9800.0     23-09-2026
496    ICD10 S52          9400.0     24-09-2026
497    ICD10 I21         14200.0     25-09-2026
498    ICD10 E11          4900.0     23-09-2026
499    ICD10 I63         13900.0     26-09-2026

[500 rows x 9 columns]>

In [38]:
df.isnull()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

In [39]:
df.isnull().sum()

Patient_ID            0
Gender                0
Age                   0
Medical_Condition     0
Admission_Date        0
Admission_Type        0
Medical_Code         15
Billing_Amount        0
Discharge_Date        0
dtype: int64

In [40]:
df['Medical_Code'].isnull().sum()

np.int64(15)

In [41]:
df['Medical_Code']=df['Medical_Condition'].fillna('unknown')

In [42]:
df['Medical_Code'].isnull().sum()

np.int64(0)

In [43]:
df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])
df['Discharge_Date']

/tmp/ipykernel_1023/399764853.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
/tmp/ipykernel_1023/399764853.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])

0     2026-01-20
1     2026-01-22
2     2026-01-18
3     2026-01-19
4     2026-01-25
         ...
495   2026-09-23
496   2026-09-24
497   2026-09-25
498   2026-09-23
499   2026-09-26
Name: Discharge_Date, Length: 500, dtype: datetime64[ns]

In [44]:
df["Admission_Type"]=(
    df["Admission_Type"]
    .str.strip()
    .str.lower()
)

In [45]:
df['Admission_Type'].value_counts()

Admission_Type
routine      196
emergency    188
urgent       116
Name: count, dtype: int64

In [46]:
df['Billing_Amount'].describe()

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64

In [47]:
df['Stay_Days']=(df['Discharge_Date']-df['Admission_Date']).dt.days
df['Stay_Days']

0      5
1      6
2      2
3      2
4      8
      ..
495    3
496    4
497    4
498    2
499    4
Name: Stay_Days, Length: 500, dtype: int64

In [48]:
df['Stay_Days'].describe()

count    500.00000
mean       2.74400
std        1.17696
min        1.00000
25%        2.00000
50%        2.00000
75%        4.00000
max       10.00000
Name: Stay_Days, dtype: float64

In [50]:
pd.crosstab(df['Medical_Condition'],df['Gender'])

Gender                   Female  Male
Medical_Condition
Allergic Reaction            14     1
Anxiety Disorder              2     7
Appendicitis                  8    25
Asthma                        8    11
Back Pain                     5    15
COPD                         16    18
Diabetes Type 1              12     3
Diabetes Type 2               6    10
Fracture                      7    15
Gallstones                    3    12
Gastritis                    11    10
Heart Attack                 15    12
Heart Failure                10    20
Hypertension                 19     9
Hypothyroidism                1     0
Kidney Stone                 10    18
Migraine                      6     0
Osteoarthritis                6     6
Osteoporosis                  8     4
Parkinson's Disease           9    10
Pneumonia                    18    13
Pregnancy                    14     2
Skin Infection               12     8
Stroke                       16    17
Urinary Tract Infection      14     4